import {
  useCallback,
  useEffect,
  useRef,
  useState,
} from 'react'
import {
  useNavigate,
  useSearch,
} from '@tanstack/react-router'
import { useLoginWithCredentials } from '../hooks/useLoginWithCredentials'
import { useLoginWithToken } from '../hooks/useLoginWithToken'
import {
  homeForRole,
  setSession,
} from '../../../app/auth/session'
import type { AuthSession } from '../types/auth.types'

export function LoginPage() {
  const navigate = useNavigate()
  const search = useSearch({ from: '/login' })
  const tokenParam = search.token

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const credentialsMutation =
    useLoginWithCredentials()
  const tokenMutation = useLoginWithToken()
  const autoAttempted = useRef(false)

  const handleSessionCreated = useCallback(
    (session: AuthSession) => {
      setSession(session)
      navigate({
        to: homeForRole(
          session.user.role as never,
          session.user.departmentType,
        ) as never,
      })
    },
    [navigate],
  )

  useEffect(() => {
    if (!tokenParam || autoAttempted.current) {
      return
    }

    autoAttempted.current = true

    tokenMutation.mutate(tokenParam, {
      onSuccess: handleSessionCreated,
    })
  }, [
    tokenParam,
    tokenMutation,
    handleSessionCreated,
  ])

  function handleCredentialsSubmit(
    event: React.FormEvent<HTMLFormElement>,
  ) {
    event.preventDefault()

    credentialsMutation.mutate(
      { email, password },
      {
        onSuccess: handleSessionCreated,
      },
    )
  }

  const credentialsError =
    credentialsMutation.error?.message

  const tokenError = tokenMutation.error?.message

  const showAutoLogin =
    Boolean(tokenParam) &&
    !tokenMutation.isError

  if (showAutoLogin) {
    return (
      <main className="auth-page">
        <div className="auth-card">
          <div className="auth-brand">
            <div className="brand-mark">S</div>

            <div>
              <strong>SMSF</strong>
              <span>Admin Portal</span>
            </div>
          </div>

          <div className="loading-state">
            Signing you in with your access link...
          </div>
        </div>
      </main>
    )
  }

  return (
    <main className="auth-page">
      <div className="auth-card">
        <div className="auth-brand">
          <div className="brand-mark">S</div>

          <div>
            <strong>SMSF</strong>
            <span>Admin Portal</span>
          </div>
        </div>

        <h1>Sign in</h1>

        <p className="auth-subtitle">
          Admin signs in with email and password.
          Head or user opens the access link
          generated by the admin — they land
          directly on their dashboard.
        </p>

        {tokenParam && tokenError && (
          <p className="auth-error">
            Access link invalid or revoked:{' '}
            {tokenError}
          </p>
        )}

        <form
          className="auth-form"
          onSubmit={handleCredentialsSubmit}
        >
          <label>
            Email Address

            <input
              required
              type="email"
              value={email}
              onChange={(event) =>
                setEmail(event.target.value)
              }
              placeholder="name@company.com"
              autoComplete="username"
            />
          </label>

          <label>
            Password

            <input
              required
              type="password"
              minLength={6}
              value={password}
              onChange={(event) =>
                setPassword(event.target.value)
              }
              placeholder="••••••••"
              autoComplete="current-password"
            />
          </label>

          {credentialsError && (
            <p className="auth-error">
              {credentialsError}
            </p>
          )}

          <button
            type="submit"
            className="primary-button auth-submit"
            disabled={credentialsMutation.isPending}
          >
            {credentialsMutation.isPending
              ? 'Signing in...'
              : 'Sign in as Admin'}
          </button>
        </form>
      </div>
    </main>
  )
}






